services:
    CoreShop\Bundle\RuleBundle\Command\RuleAvailabilityProcessorCommand:
        arguments:
            - '@coreshop.rule_availability_processor'
        tags:
          - { name: console.command, command: coreshop:rules:check-availability }
