services:

    coreshop.rule_availability_processor:
        class: CoreShop\Bundle\RuleBundle\Processor\RuleAvailabilityProcessor
        arguments:
            - '@event_dispatcher'
            - '@doctrine.orm.default_entity_manager'
            - '@coreshop.registry.rule_availability_assessor'

    coreshop.registry.rule_availability_assessor:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - 'CoreShop\Component\Rule\Condition\Assessor\RuleAvailabilityAssessorInterface'
            - 'rule-availability-assessor'

    coreshop.rule.availability_assessor.cart_price:
        class: CoreShop\Bundle\RuleBundle\Assessor\RuleAvailabilityAssessor
        arguments:
             - '@coreshop.repository.cart_price_rule'
        tags:
            - { name: coreshop.registry.rule_availability_assessor, type: cart_price }

    coreshop.rule.availability_assessor.product_price:
        class: CoreShop\Bundle\RuleBundle\Assessor\RuleAvailabilityAssessor
        arguments:
             - '@coreshop.repository.product_price_rule'
        tags:
            - { name: coreshop.registry.rule_availability_assessor, type: product_price }

    coreshop.rule.availability_assessor.product_specific_price:
        class: CoreShop\Bundle\RuleBundle\Assessor\RuleAvailabilityAssessor
        arguments:
             - '@coreshop.repository.product_specific_price_rule'
        tags:
            - { name: coreshop.registry.rule_availability_assessor, type: product_specific_price }