CoreShop\Component\Rule\Model\Action:
    type: mappedSuperclass
    table: coreshop_rule_action
    fields:
        id:
            type: integer
            column: id
            id: true
            generator:
                strategy: AUTO
        type:
            column: type
            type: string
        sort:
            column: sort
            type: integer
            nullable: true
        configuration:
            column: configuration
            type: array
            nullable: true
